In [9]:
import cv2
import os
from tqdm import tqdm
from random import shuffle
#pip install tqdm
 

In [10]:
train='D:/train/train'
predict='D:/test1/test1'
 
def label_img(img):
    label=img.split('.')
    if label[0]=='cat':
        return 0
    elif label[0]=='dog':
        return 1
 

In [11]:
train_data=[]
def feature_data():
    for i in tqdm(os.listdir(train)):
        label=label_img(i)
        path=os.path.join(train,i)
        feature=cv2.imread(path,0)
        feature=cv2.resize(feature,(50,50))
        train_data.append([[feature],[label]])
    shuffle(train_data)
    return train_data

In [12]:
training=feature_data()

100%|████████████████████████████████████████████████████████████████████████████| 25000/25000 [09:27<00:00, 72.49it/s]


In [46]:
import numpy as np
training=np.array(training).reshape(25000,2)
training.shape
#25000x2

(25000, 2)

In [61]:
training[0][0]

array([[ 94, 136, 119, ..., 237, 255, 255],
       [104, 123, 120, ...,  91, 255, 255],
       [103, 113, 113, ...,  88, 255, 255],
       ...,
       [255, 194, 180, ..., 188, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [18]:
#25000x25001
m=np.array([[[3,6,7,8],[0]],
           [[2,9,7,12],[1]],
            [[13,60,17,8],[0]]])

In [20]:
m.shape

(3, 2)

In [59]:
ar=np.zeros([2500,2501])

In [53]:
np.array(a).shape

(3, 5)

In [55]:
f


ValueError: could not broadcast input array from shape (2) into shape (5)

In [45]:
m=np.array([[[3,6,7,8],[0]],
           [[2,9,7,12],[1]],
            [[13,60,17,8],[0]]])
a=np.zeros([3,5])
for i in range(3):
    a[i]=np.hstack((m[i][0],m[i][1]))
a

array([[ 3.,  6.,  7.,  8.,  0.],
       [ 2.,  9.,  7., 12.,  1.],
       [13., 60., 17.,  8.,  0.]])

In [68]:
train_ar=np.zeros([25000,2501])
for i in range(25000):
    train_ar[i]=np.hstack((training[i][0].ravel(),training[i][1]))
    
train_ar

array([[ 94., 136., 119., ..., 255., 255.,   1.],
       [ 95., 109., 116., ..., 159., 252.,   1.],
       [ 53.,  67.,  75., ...,  88.,  86.,   1.],
       ...,
       [ 35.,  39.,  15., ..., 144., 173.,   1.],
       [249., 249., 249., ..., 242., 244.,   0.],
       [ 34.,  35.,  38., ...,  35.,  23.,   0.]])

In [69]:
x=train_ar[:,:-1]
y=train_ar[:,-1:]